import React, { useRef, useEffect, useState } from 'react';
import { GenerationStep } from '../types';
import { Eye, ArrowDown, Sparkles } from 'lucide-react';

interface Props {
  steps: GenerationStep[];
  currentAnimStep?: GenerationStep | null;
  stage?: string;
  selectedStepIndex: number | null;
  onStepClick: (index: number) => void;
  showTokenBoundaries: boolean;
  setShowTokenBoundaries: (v: boolean) => void;
  isGenerating: boolean;
}

interface TokenButtonProps {
  step: GenerationStep;
  isSelected: boolean;
  isAnimActive?: boolean;
  showTokenBoundaries: boolean;
  onClick: (index: number) => void;
}

const TokenButton = React.memo(function TokenButton({
  step,
  isSelected,
  isAnimActive,
  showTokenBoundaries,
  onClick
}: TokenButtonProps) {
  const isNewline = step.tokenText.includes('\n');
  const displaySpace = showTokenBoundaries && !isNewline && /^\s+$/.test(step.tokenText);
  const displayNewline = showTokenBoundaries && isNewline;

  return (
    <button
      type="button"
      onClick={() => onClick(step.index)}
      className={`
        relative inline-block text-left font-mono transition-all rounded px-0.5 focus-ring
        ${showTokenBoundaries ? 'border border-border-strong mx-[1px] my-[1px] bg-surface-raised hover:border-primary-500' : 'hover:bg-surface-raised'}
        ${isSelected ? 'bg-primary-500/20 text-text-main border-primary-500 shadow-sm ring-1 ring-primary-500 font-semibold' : ''}
        ${isAnimActive ? 'ring-2 ring-primary-500 bg-primary-500/25 text-emerald-800 dark:text-emerald-300 font-bold animate-pulse shadow-sm dark:shadow-[0_0_12px_rgba(16,185,129,0.5)]' : ''}
      `}
      title={`Token #${step.index}: "${step.tokenText.replace(/\n/g, '\\n')}" | Prob: ${(step.probability * 100).toFixed(1)}% | Latency: ${step.deltaLatency.toFixed(0)}ms`}
      aria-label={`Token ${step.index}: ${step.tokenText.trim() || 'whitespace'}`}
    >
      {displayNewline && (
        <span className="text-text-muted/40 select-none pointer-events-none text-[10px] font-mono ml-0.5">
          ↵{'\n'}
        </span>
      )}
      {displaySpace && (
        <span className="text-text-muted/30 select-none pointer-events-none text-[10px] font-mono px-0.5">
          ·
        </span>
      )}
      <span>{step.tokenText}</span>
    </button>
  );
});

export function GeneratedTextView({
  steps,
  currentAnimStep,
  stage,
  selectedStepIndex,
  onStepClick,
  showTokenBoundaries,
  setShowTokenBoundaries,
  isGenerating
}: Props) {
  const containerRef = useRef<HTMLDivElement>(null);
  const autoScrollRef = useRef(true);
  const [userScrolledUp, setUserScrolledUp] = useState(false);

  // Auto-scroll logic
  useEffect(() => {
    const container = containerRef.current;
    if (!container || !isGenerating || !autoScrollRef.current) return;
    container.scrollTop = container.scrollHeight;
  }, [steps, isGenerating]);

  const handleScroll = () => {
    const container = containerRef.current;
    if (!container) return;
    const isAtBottom = container.scrollHeight - container.scrollTop - container.clientHeight < 20;
    autoScrollRef.current = isAtBottom;
    setUserScrolledUp(!isAtBottom && isGenerating);
  };

  const resumeAutoScroll = () => {
    const container = containerRef.current;
    if (!container) return;
    container.scrollTop = container.scrollHeight;
    autoScrollRef.current = true;
    setUserScrolledUp(false);
  };

  return (
    <div className="bg-surface border border-border rounded-2xl p-5 flex flex-col h-full min-h-[400px] max-h-[calc(100vh-140px)] shadow-sm dark:shadow-xl relative font-sans">
      {/* Header */}
      <div className="flex flex-col mb-3 gap-1.5 border-b border-border-subtle pb-3">
        <div className="flex justify-between items-center">
          <div className="flex items-center gap-2">
            <Eye className="w-4 h-4 text-primary-500" />
            <h3 className="font-mono font-bold text-xs uppercase tracking-wider text-text-main">
              Generated Stream Output
            </h3>
          </div>

          <label className="flex items-center gap-2 text-xs text-text-muted cursor-pointer hover:text-text-main transition-colors select-none">
            <input
              type="checkbox"
              checked={showTokenBoundaries}
              onChange={(e) => setShowTokenBoundaries(e.target.checked)}
              className="w-4 h-4 rounded border-border-strong bg-surface text-primary-600 focus:ring-primary-500 focus:ring-offset-background cursor-pointer"
            />
            <span className="font-mono text-[11px]">Show Boundaries</span>
          </label>
        </div>

        {showTokenBoundaries && (
          <div className="text-[11px] font-mono text-primary-600 dark:text-emerald-400 leading-tight">
            Each outlined box represents one individual token generated by the model. Click any token to inspect its step logprobs.
          </div>
        )}
      </div>

      {/* Main Text Content Box */}
      <div
        ref={containerRef}
        onScroll={handleScroll}
        className="flex-1 bg-surface-raised border border-border rounded-xl p-4 overflow-y-auto font-mono text-sm leading-relaxed whitespace-pre-wrap relative shadow-inner scrollbar-hide text-text-main"
      >
        {steps.map((step) => (
          <TokenButton
            key={step.index}
            step={step}
            isSelected={selectedStepIndex === step.index}
            isAnimActive={Boolean(currentAnimStep && currentAnimStep.index === step.index)}
            showTokenBoundaries={showTokenBoundaries}
            onClick={onStepClick}
          />
        ))}

        {currentAnimStep && !steps.find((s) => s.index === currentAnimStep.index) && (stage === 'selection' || stage === 'token' || stage === 'append') && (
          <span
            key={`anim-${currentAnimStep.index}`}
            className="inline-block relative px-1 py-0.5 rounded bg-primary-500/20 text-emerald-800 dark:text-emerald-300 font-bold border border-primary-500/40 animate-pulse shadow-sm dark:shadow-[0_0_12px_rgba(16,185,129,0.4)]"
          >
            {currentAnimStep.tokenText}
          </span>
        )}

        {steps.length === 0 && !currentAnimStep && (
          <div className="flex flex-col items-center justify-center h-full text-center text-text-muted/60 py-12 gap-2">
            <Sparkles className="w-6 h-6 text-text-muted/40" />
            <span className="text-xs font-mono">
              Ready. Enter a prompt above and start generation.
            </span>
          </div>
        )}
      </div>

      {/* Floating Resume Auto-Scroll Button */}
      {userScrolledUp && (
        <button
          onClick={resumeAutoScroll}
          className="absolute bottom-8 right-8 z-20 flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-primary text-white dark:text-black font-mono font-bold text-xs shadow-md dark:shadow-[0_4px_16px_rgba(16,185,129,0.4)] hover:bg-emerald-700 dark:hover:bg-emerald-400 transition-transform active:scale-95"
        >
          <ArrowDown className="w-3.5 h-3.5" />
          <span>Resume Scroll</span>
        </button>
      )}
    </div>
  );
}
